### ISSUE TITLE
Kindly update script for sonarr v3

### ISSUE THREAD

**Issue by shad90** [ruia/SonarrExternalPlayer#2]
I have been using this script for more  than a year and it is really convenient . Kindly update it for sonar v3. I don't know much of programming thx

**Comment by ruia** [comment]
Hello again!

Just pushed an updated version, please test and let me know if it works!
Tested on my maniche against Sonarr v2 and v3, installed on localhost and both worked fine.

Best regards

**Comment by shad90** [comment]
Thank You, Sir. It is working like charm.

**Comment by ruia** [comment]
Glad it worked! 🙂
