### ISSUE TITLE
Script not working with new update 

### ISSUE THREAD

**Issue by shad90** [ruia/SonarrExternalPlayer#3]
Hey
Its me again.
Script is not working after new update
They might have changed something about episode summary.
I tried but failed. Kindly update your scripts
Regards

**Comment by shad90** [comment]
Hey there. 
So i have tried and made crude form of your script. and it is working with new update. 
Pasting that code here. Your version will be cleaner so i am still waiting for that.
Or give me some guideline on how can i improve on this. 

`
  var selector = '[class^="EpisodeSummary"]';
  var waitForEl = function(selector, callback) {
    if (jQuery(selector).length) {
      callback();
    }
    else {
      setTimeout(function() {
        waitForEl(selector, callback);
      }, 100);
    }
  };
  waitForEl(selector, function() {
  
      var bindClicks = function() {
          var hasBtn = false;
          var version = -1;
  
          if (version == -1) {
              version = parseFloat(jQuery(".version").text());
          }
          debugger;
          if (version == 2) {
              var table = jQuery(".episode-file-info");
              var tableHeader = table.find("thead tr");
              var tableBody = table.find("tbody");
  
              if (tableHeader.children().first().text() == "Play") {
                  hasBtn = true;
              }
  
              if(!hasBtn) {
                  tableHeader.prepend("<th>Play</th>");
  
                  tableBody.children('tr').each(function(i, e) {
                      jQuery(e).prepend('<td><button><i class="icon-sonarr-active"><i></button></td>');
                      jQuery(e.children[0]).click({filename: e.children[1].innerText, }, OpenExternalPlayer);
                  });
              }
          } else {
              //var filesHeader = jQuery('[class^="EpisodeSummary/filesHeader/"]');
              var filesHeader = jQuery('[class^="EpisodeSummary"]').next('[class^="Table"]').find("tr").first().get(0).children;
              //var filesBody = jQuery('[class^="EpisodeSummary/fileRow/"]');
              var filesBody = jQuery('[class^="EpisodeSummary"]').next('[class^="Table"]').find("tr").get(1).children;
              ;
  
              //if (filesHeader.children().first().text() == "Play") {
              if (filesHeader[0].textContent == "Play") {
                  hasBtn = true;
              }
  
              if(!hasBtn) {
                  //filesHeader.prepend('<div style="flex: 0 0 40px">Play</div>');
                  $('<th class="TableHeaderCell-headerCell-2wg3X">Play</th>').insertBefore(filesHeader[0]);
                  //filesBody.each(function(i, e) {
                      //                jQuery(e).prepend('<div style="flex: 0 0 40px"><a style="color: inherit" href="#"><svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="play" class="svg-inline--fa fa-play fa-w-14 Icon/default/3C-KJ" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="font-size: 14px;"><path fill="currentColor" d="M424.4 214.7L72.4 6.6C43.8-10.3 0 6.1 0 47.9V464c0 37.5 40.7 60.1 72.4 41.3l352-208c31.4-18.5 31.5-64.1 0-82.6z"></path></svg></a></div>');
                      $('<td style="flex: 0 0 40px"><a style="color: inherit" href="#"><svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="play" class="svg-inline--fa fa-play fa-w-14 Icon/default/3C-KJ" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="font-size: 14px;"><path fill="currentColor" d="M424.4 214.7L72.4 6.6C43.8-10.3 0 6.1 0 47.9V464c0 37.5 40.7 60.1 72.4 41.3l352-208c31.4-18.5 31.5-64.1 0-82.6z"></path></svg></a></td>').insertBefore(filesBody[0]);
                      //jQuery(e.children[0]).click({filename: e.children[1].innerText, }, OpenExternalPlayer);
                      jQuery(filesBody[0]).click({filename: filesBody[1].textContent, }, OpenExternalPlayer);
                 // });
              }
          }
      };
  
      setInterval(bindClicks, 100);
      bindClicks();
  });
`

Also kindly inform me how you were able to get info using`//var filesHeader = jQuery('[class^="EpisodeSummary/filesHeader/"]');` I had to traverse children elements to get to that information. Same thing for filesBody.

**Comment by ruia** [comment]
Hello,

Sorry for the delay! The work lately has been crazy.

Just updated the script to work with the current version of Sonarr: 3.0.6.1265. I tested on my local machine and it worked fine.

> Also kindly inform me how you were able to get info using//var filesHeader = jQuery('[class^="EpisodeSummary/filesHeader/"]'); I had to traverse children elements to get to that information. Same thing for filesBody.

Regarding this, Sonarr on the previous versions had diferent tags and classes, on this new version its style is much more like version 2 (back to tables instead of divs and such).


Let me now if it doesn't work or fails in the future.


Rui

**Comment by shad90** [comment]
It is working. Thx for taking the time.
